### ISSUE TITLE
User can set goal weight

### ISSUE THREAD

**Issue by yesseniarod** [yesseniarod/simply-calories#1]
## 💰 Motivation

User can set goal weight

## 📐 Plan

Allow users to enter current physique status and set target weight

## 🖼️ Wireframe

![Screen Shot 2021-04-08 at 11 19 38 AM](https://user-images.githubusercontent.com/74885918/114079425-09489980-985f-11eb-8f72-b04368856b2a.png)

![Screen Shot 2021-04-08 at 11 20 24 AM](https://user-images.githubusercontent.com/74885918/114079381-fd5cd780-985e-11eb-8353-cdeb120913e2.png)

## ✅ Task List

- [x] Create a form react component
- [x] Make all form inputs required 
- [x] listen for onChange events on form
- [x] listen for onSubmit events on form
- [x] Add header 
- [x] Ensure that the form looks nice on both mobile-sized and desktop-sized screens
- [x] Create database and add table to schema.sql
- [x] Add user data to data.sql
- [x] Require pg and make new Pool
- [x] Create POST route  
- [x] Query database
- [x] Handle client errors and successful request
- [x] Test functionality 
- [x] Remove CSS styling that had no affect or was otherwise unnecessary
- [x] Fix all errors
