### ISSUE TITLE
User can sign in

### ISSUE THREAD

**Issue by yesseniarod** [yesseniarod/simply-calories#10]
## 💰 Motivation
User can sign in 

## 📐 Plan
User should be able to log into existing account

## 🖼️ Wireframe
![Screen Shot 2021-05-11 at 1 47 29 PM](https://user-images.githubusercontent.com/74885918/117882684-70db7580-b25f-11eb-8232-c13224c464c9.png)

![Screen Shot 2021-05-11 at 1 50 00 PM](https://user-images.githubusercontent.com/74885918/117883048-c9127780-b25f-11eb-8248-169a7fcef150.png)

## ✅ Task List

- [x] Add a token to .env (don't forget about heroku before merging)
- [x] Modify handleSubmit to be able to differ between sign in and sign up
- [x] Create a server POST route to check username and password
- [x] Make a handleSignIn function
- [x] Inform user if credentials are incorrect
- [x] Verify that usernames are unique
- [x] Successful sign in should redirect user
- [x] Decode token
- [x] Make a handleSignOut function
- [x] Verify that user stats transfer to summary table
- [x] Test functionality
- [x] Fix bugs
- [x] Remove comments
- [x] Touch ups
