### ISSUE TITLE
User can determine daily calories

### ISSUE THREAD

**Issue by yesseniarod** [yesseniarod/simply-calories#2]
## 💰 Motivation
User can determine recommended daily calorie intake

## 📐 Plan
Daily calorie intake will be calculated based off of user's form inputs (height, age, gender, weight, target weight, activity)

## 🖼️ Wireframe

![Screen Shot 2021-04-09 at 1 22 15 PM](https://user-images.githubusercontent.com/74885918/114236582-a7f3f980-9936-11eb-9a89-6f451107579e.png)

![Screen Shot 2021-04-09 at 1 10 07 PM](https://user-images.githubusercontent.com/74885918/114235393-f6a09400-9934-11eb-8ba8-a8f88e2a04d3.png)

## ✅ Task List

- [x] Create a function that calculates daily calorie intake
- [x] Create a table class component
- [x] Make GET route that retrieves user's information
- [x] Create setUser method and pass to form via props
- [x] Pass user information to table via props
- [x] Listen for hash change events on the window object
- [x] Ensure styling looks nice in both mobile and desktop 
- [x] Remove unnecessary styling and fix bugs 🐞
- [x] Remove comments
