### ISSUE TITLE
User can register

### ISSUE THREAD

**Issue by yesseniarod** [yesseniarod/simply-calories#23]
## 💰 Motivation
User can create an account

## 📐 Plan
Allow user to create an account to keep track of entries

## 🖼️ Wireframe
![Screen Shot 2021-04-30 at 4 17 14 PM](https://user-images.githubusercontent.com/74885918/116762947-ed08ca00-a9d0-11eb-8d9d-e6d12906e09c.png)
![Screen Shot 2021-04-30 at 4 23 00 PM](https://user-images.githubusercontent.com/74885918/116762933-e24e3500-a9d0-11eb-815e-845ec03f13f7.png)

## ✅ Task List

- [x] Create a form component 
- [x] Make handle change function
- [x] Make a handle submit function 
- [x] Create a schema and import it 
- [x] Create a POST server route to check username and password
- [x] Add a POST fetch request to handle submit function
- [x] Test functionality
- [x] Add minimum password length requirement
- [x] Hide navigation 
- [x] Remove unnecessary styling
- [x] Fix bugs
- [x] Final touch up
