### ISSUE TITLE
User can search food items

### ISSUE THREAD

**Issue by yesseniarod** [yesseniarod/simply-calories#3]
## 💰 Motivation
User can search for food items 

## 📐 Plan
User can search for specific food items to enter in their food journal

## 🖼️ Wireframe
![Screen Shot 2021-04-12 at 11 10 29 AM](https://user-images.githubusercontent.com/74885918/114441193-edefce00-9b7f-11eb-9a1b-a4bbcb78beab.png)
![Screen Shot 2021-04-12 at 11 11 49 AM](https://user-images.githubusercontent.com/74885918/114441210-f34d1880-9b7f-11eb-82eb-c37f9914ac72.png)

## ✅ Task List
- [x] Add modalOpen property to state
- [x] Make a button and listen for onClick events 
- [x] Create a modal that opens when button is clicked
- [x] Clicking outside of modal should close modal
- [x] Redirect user when 'Food journal' is clicked 
- [x] Create search bar component
- [x] Make a function getFoodItem that will make a get request to API
- [x] Make a function handleInput that will handle user's input
- [x] Make a function handleSearch and mearge with getFoodItem
- [x] Remove unnecessary styling and fix bugs
- [x] Remove comments
