### ISSUE TITLE
User can log daily calorie intake

### ISSUE THREAD

**Issue by yesseniarod** [yesseniarod/simply-calories#4]
## 💰 Motivation
User is able to log daily calorie intake.

## 📐 Plan
User can view search results and log calorie consumption in food journal

## 🖼️ Wireframe
![Screen Shot 2021-04-13 at 3 15 24 PM](https://user-images.githubusercontent.com/74885918/114628027-14d6fe80-9c6b-11eb-876b-7bd707a77675.png)
![Screen Shot 2021-04-13 at 3 12 36 PM](https://user-images.githubusercontent.com/74885918/114627813-bc9ffc80-9c6a-11eb-9b96-909001296d9e.png)

## ✅ Task List

- [x] Display search results
- [x] Make a function that selects li element
- [x] Selecting li element should add it to calories and items array in this state
- [x] Create a table to send selected items 
- [x] Add font awesome icon and listen for onClick event
- [x] Clicking 'add icon' should add food item to items array 
- [x] Test functionality 
- [x] Remove unnecessary CSS styling
- [x] Fix all bugs 🐞
