### ISSUE TITLE
User can view food journal entries

### ISSUE THREAD

**Issue by yesseniarod** [yesseniarod/simply-calories#5]
## 💰 Motivation
User can view food journal entries

## 📐 Plan
User should be able to look at entries in food journal 

## 🖼️ Wireframe

![Screen Shot 2021-04-13 at 5 31 47 PM](https://user-images.githubusercontent.com/74885918/114637516-689f1300-9c7e-11eb-869d-9ae89b6fec63.png)
![Screen Shot 2021-04-14 at 3 43 27 PM](https://user-images.githubusercontent.com/74885918/114789600-34882880-9d38-11eb-89c2-910c7b38e057.png)

## ✅ Task List

- [x] Make a GET route for server
- [x] Make an entries-list component and fetch all entries
- [x] Map thorugh the items array to display on page
- [x] Make sure image and food description is retrieved 
- [x] Determine total calories for journal entries
- [x] Add an anchor tag that redirect user to entry-list
- [x] Add navigation for mobile and desktop
- [x] Remove unnecessary CSS styling 
- [x] Fix all bugs 🐞
- [x] Remove comments
