### ISSUE TITLE
User can search for exercises

### ISSUE THREAD

**Issue by yesseniarod** [yesseniarod/simply-calories#6]
## 💰 Motivation
User can search for exercises 

## 📐 Plan
User is able to search for exercises to log to workout journal

## 🖼️ Wireframe
![Screen Shot 2021-04-16 at 11 20 06 AM](https://user-images.githubusercontent.com/74885918/115067425-bd70a280-9ea5-11eb-9e00-429ddc339581.png)

![Screen Shot 2021-04-16 at 11 18 19 AM](https://user-images.githubusercontent.com/74885918/115067267-83070580-9ea5-11eb-8f86-c470855ae325.png)

## ✅ Task List

- [x] Create a wokout journal page
- [x] Clicking on weight icon on modal should redirect user to workout journal page
- [x] Create a SearchExercise component 
- [x] Create a function to handle user input
- [x] Make a function to fetch API
- [x] Test functionality
- [x] Remove unnecessary styling and comments
