### ISSUE TITLE
User can log exercise activity

### ISSUE THREAD

**Issue by yesseniarod** [yesseniarod/simply-calories#7]
## 💰 Motivation
User can log exercise activity

## 📐 Plan
User should be able to add exercise activity to workout journal

## 🖼️ Wireframe

![Screen Shot 2021-04-16 at 11 08 57 AM](https://user-images.githubusercontent.com/74885918/115066388-4d155180-9ea4-11eb-886d-96658b3d1881.png)

![Screen Shot 2021-04-16 at 11 12 15 AM](https://user-images.githubusercontent.com/74885918/115066606-a1b8cc80-9ea4-11eb-9dbe-67ea08ad3525.png)

## ✅ Task List

- [x] Display search results by mapping through result array
- [x] Add font awesome icon 
- [x] Add data attributes
- [x] Make a function that selects li elements 
- [x] Create a table to send selected items
- [x] npm run db:import
- [x] Make a fetch POST request in selectExercise
- [x] Make a POST route for server
- [x] Clicking 'add icon' should add activity to items array
- [x] Remove unnecessary CSS styling
- [x] Fix bugs
