### ISSUE TITLE
User can view workout journal entries

### ISSUE THREAD

**Issue by yesseniarod** [yesseniarod/simply-calories#8]
## 💰 Motivation
User can view workout journal entries

## 📐 Plan
User should be able to view entries in workout journal

## 🖼️ Wireframe

![Screen Shot 2021-04-16 at 4 11 13 PM](https://user-images.githubusercontent.com/74885918/115093594-be1e2e80-9ecf-11eb-8f44-6d02d3213ea9.png)
![Screen Shot 2021-04-16 at 4 20 36 PM](https://user-images.githubusercontent.com/74885918/115093586-b9597a80-9ecf-11eb-80b0-55d497a2e43a.png)

## ✅ Task List

- [x] Create a WorkoutEntries component
- [x] Make a GET route to server
- [x] Fetch entries
- [x] Create componentDidMount function
- [x] Map through items array to display on page
- [x] Determine total calories
- [x] Add on anchor tag to redirect user 
- [x] Fix bugs
- [x] Remove unnecessary styling and comments
