### ISSUE TITLE
User can determine remaining daily calories

### ISSUE THREAD

**Issue by yesseniarod** [yesseniarod/simply-calories#9]
## 💰 Motivation
User can determine remaining daily calories

## 📐 Plan
User should be able to determine remaining daily calories while taking into consideration calories consumed and calories burned

## 🖼️ Wireframe

![Screen Shot 2021-04-23 at 11 18 38 AM](https://user-images.githubusercontent.com/74885918/115913962-261bca00-a426-11eb-9194-a3a49c3ad62b.png)

![Screen Shot 2021-04-23 at 11 21 24 AM](https://user-images.githubusercontent.com/74885918/115913942-1e5c2580-a426-11eb-99d9-dc6bfd6dc4ce.png)

![Screen Shot 2021-04-22 at 5 54 26 PM](https://user-images.githubusercontent.com/74885918/115802575-063bc600-a394-11eb-9780-570dc38f0d61.png)
![Screen Shot 2021-04-22 at 5 47 52 PM](https://user-images.githubusercontent.com/74885918/115802579-06d45c80-a394-11eb-9fd1-bc68abea0a2a.png)

## ✅ Task List
- [x] Create a getFoodEntries function that fetches food entries from the database
- [x] Create a getWorkoutEntries function that fetches workout entries from the database
- [x] Update summary table to show consumed, burned, and net calories
- [x] Make a landing page for app
- [x] Make modifications to navigation
- [x] Test functionality
- [x] Remove unnecessary CSS 
- [x] Fix bugs
- [x] Test functionality again
